# Generated by Django 5.1.1 on 2024-10-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_nacimiento',
        ),
    ]
